"""courseId added to deadlines table

Revision ID: 010a33d8883e
Revises: f6ebe9acff55
Create Date: 2025-02-14 00:18:33.858862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '010a33d8883e'
down_revision: Union[str, None] = 'f6ebe9acff55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deadlines', sa.Column('course_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'deadlines', 'courses', ['course_id'], ['id'])
    op.drop_column('deadlines', 'subject')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deadlines', sa.Column('subject', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'deadlines', type_='foreignkey')
    op.drop_column('deadlines', 'course_id')
    # ### end Alembic commands ###
