"""renamed the student course column

Revision ID: 04224b208c2c
Revises: 5a7616efd886
Create Date: 2025-02-18 15:34:13.535529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '04224b208c2c'
down_revision: Union[str, None] = '5a7616efd886'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'pending_course_ids')
    op.drop_column('students', 'completed_course_ids')
    op.drop_column('students', 'current_term_course_ids')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('current_term_course_ids', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('completed_course_ids', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('pending_course_ids', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
