"""added assignment number columns

Revision ID: 0eaf812883a2
Revises: 87f66c1c1b92
Create Date: 2025-03-22 15:09:25.299285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0eaf812883a2'
down_revision: Union[str, None] = '87f66c1c1b92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('graded_assignments', sa.Column('assignment_no', sa.Integer(), nullable=True))
    op.add_column('practice_assignments', sa.Column('assignment_no', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('practice_assignments', 'assignment_no')
    op.drop_column('graded_assignments', 'assignment_no')
    # ### end Alembic commands ###
