"""upload date as datetime

Revision ID: 17cba591fac1
Revises: 87f67eed9ae2
Create Date: 2025-03-10 15:10:36.284374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17cba591fac1'
down_revision: Union[str, None] = '87f67eed9ae2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('weekwise_content', 'upload_date',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(timezone=True),
               nullable=True,
                postgresql_using="upload_date::timestamp with time zone")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('weekwise_content', 'upload_date',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
