"""new tables for weekcontent added

Revision ID: 1d9e7cb9be59
Revises: 010a33d8883e
Create Date: 2025-02-17 16:36:24.861479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d9e7cb9be59'
down_revision: Union[str, None] = '010a33d8883e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weekwise_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_no', sa.Integer(), nullable=False),
    sa.Column('term', sa.String(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('upload_date', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weekwise_content_id'), 'weekwise_content', ['id'], unique=False)
    op.create_table('graded_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('week_no', sa.Integer(), nullable=False),
    sa.Column('assignment_content', sa.JSON(), nullable=False),
    sa.Column('is_coding_assignment', sa.Boolean(), nullable=True),
    sa.Column('deadline', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['week_no'], ['weekwise_content.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_graded_assignments_id'), 'graded_assignments', ['id'], unique=False)
    op.create_table('video_lectures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('week_no', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('transcript', sa.String(), nullable=True),
    sa.Column('duration', sa.String(), nullable=False),
    sa.Column('video_link', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['week_no'], ['weekwise_content.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_lectures_id'), 'video_lectures', ['id'], unique=False)
    op.create_table('practice_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('week_no', sa.Integer(), nullable=False),
    sa.Column('lecture_id', sa.Integer(), nullable=True),
    sa.Column('assignment_content', sa.JSON(), nullable=False),
    sa.Column('is_coding_assignment', sa.Boolean(), nullable=True),
    sa.Column('deadline', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['lecture_id'], ['video_lectures.id'], ),
    sa.ForeignKeyConstraint(['week_no'], ['weekwise_content.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_practice_assignments_id'), 'practice_assignments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_practice_assignments_id'), table_name='practice_assignments')
    op.drop_table('practice_assignments')
    op.drop_index(op.f('ix_video_lectures_id'), table_name='video_lectures')
    op.drop_table('video_lectures')
    op.drop_index(op.f('ix_graded_assignments_id'), table_name='graded_assignments')
    op.drop_table('graded_assignments')
    op.drop_index(op.f('ix_weekwise_content_id'), table_name='weekwise_content')
    op.drop_table('weekwise_content')
    # ### end Alembic commands ###
