"""sync_database

Revision ID: 22b69c09ae82
Revises: 17cba591fac1
Create Date: 2025-03-10 16:08:37.042634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '22b69c09ae82'
down_revision: Union[str, None] = '17cba591fac1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('graded_assignments_week_no_fkey', 'graded_assignments', type_='foreignkey')
    op.drop_constraint('practice_assignments_week_no_fkey', 'practice_assignments', type_='foreignkey')
    op.drop_constraint('video_lectures_week_no_fkey', 'video_lectures', type_='foreignkey')
    op.alter_column('weekwise_content', 'upload_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('weekwise_content', 'upload_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.create_foreign_key('video_lectures_week_no_fkey', 'video_lectures', 'weekwise_content', ['week_no'], ['id'])
    op.create_foreign_key('practice_assignments_week_no_fkey', 'practice_assignments', 'weekwise_content', ['week_no'], ['id'])
    op.create_foreign_key('graded_assignments_week_no_fkey', 'graded_assignments', 'weekwise_content', ['week_no'], ['id'])
    # ### end Alembic commands ###
