"""added response format column in db

Revision ID: 279cf7752aa0
Revises: 6977fc1f900a
Create Date: 2025-03-24 17:54:46.761227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '279cf7752aa0'
down_revision: Union[str, None] = '6977fc1f900a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_agents', sa.Column('response_format', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_agents', 'response_format')
    # ### end Alembic commands ###
