"""added created modified and title column to conversation

Revision ID: 4106c6307c1d
Revises: 279cf7752aa0
Create Date: 2025-03-27 12:17:02.119971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4106c6307c1d'
down_revision: Union[str, None] = '279cf7752aa0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('title', sa.String(), server_default='No title.', nullable=True))
    op.add_column('conversations', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('conversations', sa.Column('modified_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'modified_at')
    op.drop_column('conversations', 'created_at')
    op.drop_column('conversations', 'title')
    # ### end Alembic commands ###
