"""added system prompt column to ai agent

Revision ID: 6977fc1f900a
Revises: 0eaf812883a2
Create Date: 2025-03-22 15:56:35.268204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6977fc1f900a'
down_revision: Union[str, None] = '0eaf812883a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_agents', sa.Column('system_prompt', sa.String(), server_default='You are helpful assistant.', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_agents', 'system_prompt')
    # ### end Alembic commands ###
