"""title and description added in assignment

Revision ID: 87f67eed9ae2
Revises: 9970c294625a
Create Date: 2025-03-10 14:17:06.668318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87f67eed9ae2'
down_revision: Union[str, None] = '9970c294625a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('graded_assignments', sa.Column('title', sa.String(), nullable=True))
    op.add_column('graded_assignments', sa.Column('description', sa.String(), nullable=True))
    op.add_column('practice_assignments', sa.Column('title', sa.String(), nullable=True))
    op.add_column('practice_assignments', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('practice_assignments', 'description')
    op.drop_column('practice_assignments', 'title')
    op.drop_column('graded_assignments', 'description')
    op.drop_column('graded_assignments', 'title')
    # ### end Alembic commands ###
