"""added lecture number column

Revision ID: 87f66c1c1b92
Revises: 5cc3478e13cd
Create Date: 2025-03-21 23:36:09.339271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87f66c1c1b92'
down_revision: Union[str, None] = '5cc3478e13cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_lectures', sa.Column('lecture_no', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video_lectures', 'lecture_no')
    # ### end Alembic commands ###
