"""add_composite_foreign_key

Revision ID: 8e8c275b95bd
Revises: 22b69c09ae82
Create Date: 2025-03-10 16:09:39.418943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e8c275b95bd'
down_revision: Union[str, None] = '22b69c09ae82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
