"""course and assignmen table modified-again-1

Revision ID: dc751b666e84
Revises: e4da1e3bcb68
Create Date: 2025-02-13 00:14:31.313261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc751b666e84'
down_revision: Union[str, None] = 'e4da1e3bcb68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
