"""course and assignmen table modified

Revision ID: dd5a5a3233f2
Revises: eec300bcaa9c
Create Date: 2025-02-13 00:09:12.742379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dd5a5a3233f2'
down_revision: Union[str, None] = 'eec300bcaa9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('icon', sa.String(), nullable=False))
    op.alter_column('deadlines', 'deadline',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('deadlines', 'deadline',
               existing_type=sa.String(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('courses', 'icon')
    # ### end Alembic commands ###
