"""course and assignmen table modified-again

Revision ID: e4da1e3bcb68
Revises: dd5a5a3233f2
Create Date: 2025-02-13 00:12:55.197661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4da1e3bcb68'
down_revision: Union[str, None] = 'dd5a5a3233f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
