"""many to many relationship added between student and courses

Revision ID: f2cf95837c04
Revises: 04224b208c2c
Create Date: 2025-02-18 16:50:15.142754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2cf95837c04'
down_revision: Union[str, None] = '04224b208c2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_current_courses',
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], )
    )
    op.drop_table('student_current_term_courses')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_current_term_courses',
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name='student_current_term_courses_course_id_fkey'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name='student_current_term_courses_student_id_fkey')
    )
    op.drop_table('student_current_courses')
    # ### end Alembic commands ###
